package myclassproject.mystorygraph;

//Fill this enum with the labels you chose for the EDGES of your story graph.
public enum MyChoiceLabels {
	GoToBarrell,
	GoToMerchantBill,
	PickUpApple, 
	WalkToFountain,
	TalkToBeggar, 
	WalkToMerchantBill,
	TalkToMerchantBill,
	WalkToForest,
	InteractWithForestPlant, 
	WalkToForestWell, 
	InteractWithBarrell, 
	InteractWithBeggar, 
	EnterForest, 
	InteractWithWell, 
	InteractWithBandit,
	ReturnToMerchant,
	InteractWithMerchant, 
	InteractWithDungeonDoor, 
	NoSwordInteractWithBandit,  
	StartGameEdges,  
	WalkToTavern, 
	SitInTavern,
	WalkToDrunkard,
	IgnoreDrunkard,
	TalkToDrunkard,
	TalkingToDrunkard,WakeUpDrunkard,
	WakeDrunkard,
	RobDrunkard,
	LeaveDrunkard,
	PersistDrunkard,
	GoToBar,
	BuyDrink,
	LeaveTavern,
	DrunkardDoor,
	atCityEdges,
	gotoBarrell,
	gotoMerchantBill,
	gotoForestPath,
	ContinueDrinkingChoice,
	GoToFireplaceChoice,
	VisitTavernTableChoice,
	BurnedToDeathChoice,
	PickupTorchChoice,

}

